name: Deploy Redoc to GitHub Pages

# トリガーの設定
on:
  push:
    branches:
      - main  # mainブランチにプッシュされたとき
  pull_request:
    types: [opened, synchronized, reopened]  # PRが作成、更新、再オープンされたとき

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'  # または任意のLTSバージョン

      - name: Install Redoc-CLI
        run: npm install -g redoc-cli

      - name: Generate Redoc HTML
        run: |
          # ブランチ名を取得
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          mkdir -p out/${BRANCH_NAME}
          redoc-cli bundle -o out/${BRANCH_NAME}/index.html schema/openapi.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
