name: Deploy Redoc to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Redoc-CLI
        run: npm install -g redoc-cli

      - name: Generate Redoc HTML
        run: |
          # ブランチ名を取得
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          # outディレクトリの指定されたブランチ名のサブフォルダにHTMLを生成
          mkdir -p out/${BRANCH_NAME}
          redoc-cli bundle -o out/${BRANCH_NAME}/index.html schema/openapi.yaml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
